### PR TITLE
Add logo graphic along with a few small improvements

### PR DESCRIPTION
**Pull request by sobering**

### CODE REVIEW

**Comment by doomspork** [comment]
@sobering have you run this locally?  If it works I'm happy to merge.

**Comment by sobering** [comment]
@doomspork Yessir, I have. She's all good.

**Comment by lpil** [comment]
LOVE that logo!

**Comment by doomspork** [comment]
@sobering made it!

**Comment by sobering** [comment]
@lpil Thanks for the compliment 🤘

**Pull request merged**
