### PR TITLE
Update jekyll version to match github recommendations

### PR DESCRIPTION
**Pull request by hedgesky**
https://pages.github.com/versions/

### CODE REVIEW

**Comment by doomspork** [comment]
Awesome @hedgesky!  Have you tested this locally or shall I pull it down?

**Comment by lpil** [comment]
Can just use the gh-pages gem :)

**Comment by doomspork** [comment]
TIL of the `gh-pages` gem.  Thanks @lpil!

**Comment by hedgesky** [comment]
OK, I'll give it a try. Thanks:)

**Comment by hedgesky** [comment]
Looks like fresh gem versions drop support for Ruby 1.9.3. Should I configure `travis.yml` to support only 2.0+?

**Comment by hedgesky** [comment]
Done. Fresh gems' versions require Ruby 2.0+ so I updated `.travis.yml` a bit. Is it OK? 
I used [this instruction](https://docs.travis-ci.com/user/customizing-the-build/#Installing-a-Second-Programming-language) to set ruby version. Using `rvm` key didn't work because whole build's language is `elixir`. Same for `.ruby-version`.

**Comment by doomspork** [comment]
@hedgesky I was just looking at the Travis config, I'm not entirely sure why we've set it up to use Elixir since this project is clearly Ruby.  It might be worth changing the whole thing.

**Comment by doomspork** [comment]
It looks like we can safely remove all of the Elixir stuff from this project, I can tackle that in a separate PR.

**Comment by hedgesky** [comment]
@doomspork I agree: here `elixir` is used to check that all Slime code is translated to HTML properly. And Slime itself doesn't look like a thing that changes frequently.
So I wait for your PR and then rebase this one onto the new master, do I?

**Comment by doomspork** [comment]
@hedgesky we can merge this and make those changes in other PRs 👍

**Pull request merged**
